### ISSUE TITLE
Add Markdownify

### ISSUE THREAD

**Issue by amitmerchant1990** [IonicaBizau/made-in-india#2]
Hi @IonicaBizau 

Would you please add my project which is based on [Electron](http://electron.atom.io)?

Here is the project itself [electron-markdownify](https://github.com/amitmerchant1990/electron-markdownify)

Thanks!

**Comment by IonicaBizau** [comment]
@amitmerchant1990 Definitely! 😁 I will rerun the build script to add the projects because some projects were missed (because of the GitHub rate limits).

Then if your project is still not listed, you can create a pull request adding it. 🚀

**Comment by amitmerchant1990** [comment]
That's great! Thanks!

**Comment by amitmerchant1990** [comment]
Awesome man! Thanks! :smiley:

**Comment by IonicaBizau** [comment]
You're welcome 😁

**Comment by amitmerchant1990** [comment]
Do give it a :star: if you like it. :+1:
